### ISSUE TITLE
Can't active plugin in Wordpress 5.4.1

### ISSUE THREAD

**Issue by nguamay** [linchpin/psst#9]
![image](https://user-images.githubusercontent.com/11470118/92370770-f03f0500-f124-11ea-9b53-af5142e82cb4.png)
Hi Bro, 
when it active plugin, it show up error,
Please help me.
Thanks

**Comment by aaronware** [comment]
Hey @nguamay this plugin doesn’t have a full install process so the dependencies aren’t committed directly to the code base. Be sure to run a “composer install” in the plugins root base/root directory so the dependencies are installed. Then try to view the admin again. I’ll update the read me for first time users in the future

**Comment by nguamay** [comment]
Thanks bro.
